<?php
/**
 * PJII - Publikasi Jurnal Ilmiah Indonesia
 * Deployment Wrapper for PHP Hosting (hPanel/CPanel)
 * 
 * This file serves as the entry point for your React application.
 * It ensures that the index.html generated by 'npm run build' is served correctly.
 */

$indexFile = __DIR__ . '/index.html';

if (file_exists($indexFile)) {
    // Set headers for better SEO and security
    header("X-Frame-Options: SAMEORIGIN");
    header("X-Content-Type-Options: nosniff");
    header("Referrer-Policy: no-referrer-when-downgrade");
    
    // Include the React build output
    include_once($indexFile);
} else {
    // Fallback if build files are missing
    http_response_code(404);
    echo "<!DOCTYPE html>
    <html lang='id'>
    <head>
        <meta charset='UTF-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1.0'>
        <title>Aplikasi Belum Siap | PJII</title>
        <style>
            body { font-family: 'Plus Jakarta Sans', sans-serif; display: flex; align-items: center; justify-content: center; height: 100vh; margin: 0; background: #f8fafc; color: #1e293b; }
            .card { background: white; padding: 40px; border-radius: 24px; shadow: 0 10px 25px -5px rgba(0,0,0,0.1); text-align: center; max-width: 400px; border: 1px solid #e2e8f0; }
            h1 { color: #0f172a; margin-bottom: 16px; }
            p { line-height: 1.6; color: #64748b; }
            code { background: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-weight: bold; }
        </style>
    </head>
    <body>
        <div class='card'>
            <h1>Aplikasi Belum Siap</h1>
            <p>File <code>index.html</code> tidak ditemukan di folder utama.</p>
            <p>Silakan jalankan <code>npm run build</code> di komputer Anda, lalu unggah <strong>ISI</strong> folder <code>dist/</code> ke folder <code>public_html</code>.</p>
        </div>
    </body>
    </html>";
}
?>
